open Szaniec_model
module Cy = Szaniec_architecture_access.Cyrograf

let generated_contract (u : Observation.unit_info) =
  u.fresh
  && List.mem
       (String.trim u.source_header)
       [ "(* Generated by Well. Do not edit. *)"
       ; "(* Generated by Cyrograf. Do not edit. *)" ]

let wrapper_segment seg =
  let prefix = "app_service_" in
  let n = String.length prefix in
  if Canonical.starts_with ~prefix (String.lowercase_ascii seg)
  then String.sub seg n (String.length seg - n)
  else seg

let bind ~approved ~(policy : Policy.t) ~(cy : Cy.t) (obs : Observation.t) =
  let bindings = Hashtbl.create 32 in
  let rejected = Hashtbl.create 8 in
  let gaps = ref [] in
  let unavailable = ref [] in
  let gap code path detail =
    gaps :=
      {Observation.gap_code= code; gap_path= path; gap_detail= detail} :: !gaps
  in
  let add (u : Observation.unit_info) (c : Cy.contract) =
    match Hashtbl.find_opt bindings u.canonical with
    | Some previous when previous <> c ->
        Hashtbl.replace rejected u.canonical () ;
        gap
          "GAP-AMBIGUOUS-OWNERSHIP"
          u.source_path
          ("conflicting contracts for " ^ u.canonical)
    | _ ->
        if u.fresh
        then Hashtbl.replace bindings u.canonical c
        else unavailable := u.canonical :: !unavailable
  in
  List.iter
    (fun (u : Observation.unit_info) ->
      List.iter
        (fun (c : Cy.contract) ->
          if
            Filename.dirname u.source_path = Filename.dirname c.contract_source
            && Cy.segment_matches_service
                 ~service:c.contract_name
                 (Filename.remove_extension (Filename.basename u.source_path))
          then add u c )
        cy.contracts )
    obs.units ;
  List.iter
    (fun (u : Observation.unit_info) ->
      if generated_contract u
      then
        let name =
          List.hd (List.rev (Canonical.split_dots u.canonical))
          |> wrapper_segment
        in
        List.iter
          (fun (c : Cy.contract) ->
            if Cy.segment_matches_service ~service:c.contract_name name
            then add u c )
          cy.contracts )
    obs.units ;
  List.iter
    (fun (b : Policy.contract_binding) ->
      let canonical =
        Canonical.resolve_alias obs.module_aliases b.contract_module
      in
      match
        ( List.find_opt
            (fun (c : Cy.contract) -> c.contract_source = b.contract_source)
            cy.contracts
        , List.find_opt
            (fun (u : Observation.unit_info) -> Some u.canonical = canonical)
            obs.units )
      with
      | Some c, Some u when u.fresh && approved -> add u c
      | _
        when (not approved)
             && Option.fold ~none:false ~some:(Hashtbl.mem bindings) canonical
        ->
          ()
      | _ ->
          unavailable :=
            (b.contract_module :: Option.to_list canonical) @ !unavailable ;
          gap
            "GAP-PUBLIC-CONTRACT"
            b.contract_source
            ( "contract binding requires approved policy and a fresh \
               source/unit: "
            ^ b.contract_module
            ^ "; verify policy.contract_bindings source/module and rebuild \
               before approving" ) )
    policy.contract_bindings ;
  Hashtbl.iter
    (fun unit () ->
      Hashtbl.remove bindings unit ;
      unavailable := unit :: !unavailable )
    rejected ;
  (bindings, List.sort_uniq compare !gaps, List.sort_uniq compare !unavailable)

let relative unit path =
  let prefix = unit ^ "." in
  if Canonical.starts_with ~prefix path
  then
    Some
      (String.sub
         path
         (String.length prefix)
         (String.length path - String.length prefix) )
  else None

let data_member ?(generated = false) (c : Cy.contract) member =
  let segments = Canonical.split_dots member in
  match segments with
  | [message; fn]
   |[message; "Storage"; fn] ->
      List.mem
        fn
        [ "make"
        ; "to_wire"
        ; "of_wire"
        ; "to_data"
        ; "from_data"
        ; "to_drut"
        ; "from_drut"
        ; "wire_of_storage"
        ; "storage_of_wire"
        ; "to_storage_value"
        ; "from_storage_value" ]
      && (generated || List.mem message c.contract_messages)
  | _ -> false

let rpc_member (cy : Cy.t) (c : Cy.contract) member =
  let name =
    match Canonical.split_dots member with
    | [name]
     |["Proxy"; name] ->
        Some name
    | _ -> None
  in
  match
    ( name
    , List.find_opt
        (fun (s : Cy.service) -> s.svc_name = c.contract_name)
        cy.services )
  with
  | Some name, Some s
    when List.exists (fun (m : Cy.method_decl) -> m.m_name = name) s.svc_methods
    ->
      Some name
  | _ -> None

let mechanic ?(generated = false) c member =
  data_member ~generated c member
  || List.mem member ["make_spec"; "spec"; "_service_ref"]

(* Value-level serializer helpers are private, not additional public codecs.
   Their dependencies need interpretation even when the public conversion
   wrapper is generated plumbing. *)
let serializer_body ?(generated = false) c member =
  data_member ~generated c member
  ||
  match Canonical.split_dots member with
  | [message; ("encode_value" | "decode_value")] ->
      generated || List.mem message c.Cy.contract_messages
  | _ -> false

let runtime_member member =
  List.mem
    member
    [ "error"
    ; "is_finite"
    ; "utf8_sequence_length"
    ; "validate_utf8"
    ; "enc_string"
    ; "enc_int"
    ; "enc_float"
    ; "enc_bool"
    ; "enc_void"
    ; "enc_record"
    ; "enc_list"
    ; "enc_option"
    ; "dec_string"
    ; "dec_int"
    ; "dec_float"
    ; "dec_bool"
    ; "dec_void"
    ; "dec_record"
    ; "dec_struct"
    ; "dec_list"
    ; "dec_option"
    ; "field"
    ; "index"
    ; "to_string"
    ; "of_string"
    ; "Syntax"
    ; "Syntax.let*"
    ; "Syntax.let+" ]

let serialization_runtimes contracts (obs : Observation.t) =
  let runtimes = Hashtbl.create 4 in
  List.iter
    (fun (runtime : Observation.unit_info) ->
      let suffix = ".Drut_runtime" in
      if runtime.fresh && Filename.check_suffix runtime.canonical suffix
      then
        let prefix =
          String.sub
            runtime.canonical
            0
            (String.length runtime.canonical - String.length "Drut_runtime")
        in
        let shape =
          List.for_all
            (fun member ->
              List.mem (runtime.canonical ^ "." ^ member) obs.defined_values )
            [ "enc_string"
            ; "dec_string"
            ; "dec_struct"
            ; "field"
            ; "index"
            ; "to_string"
            ; "of_string"
            ; "Syntax.let*"
            ; "Syntax.let+" ]
        in
        let supported_dependency unit caller target =
          match
            ( Hashtbl.find_opt contracts unit
            , List.find_opt
                (fun (u : Observation.unit_info) -> u.canonical = unit)
                obs.units
            , relative runtime.canonical target )
          with
          | Some contract, Some u, Some member ->
              shape
              && runtime_member member
              && Canonical.starts_with ~prefix unit
              && Filename.dirname runtime.source_path
                 = Filename.dirname u.source_path
              && serializer_body
                   ~generated:(generated_contract u)
                   contract
                   caller
          | _ -> false
        in
        if
          List.exists
            (fun (c : Observation.call) ->
              supported_dependency c.call_unit c.caller c.callee )
            obs.calls
          || List.exists
               (fun (v : Observation.value_ref) ->
                 supported_dependency v.ref_unit v.ref_caller v.ref_target )
               obs.value_refs
        then Hashtbl.replace runtimes runtime.canonical () )
    obs.units ;
  runtimes

let validate_surfaces
    ~approved
    ~(policy : Policy.t)
    ~(cy : Cy.t)
    (obs : Observation.t)
    ownerships =
  let gaps = ref [] in
  let resolve_unit =
    Canonical.unit_resolver
      (List.map (fun (u : Observation.unit_info) -> u.canonical) obs.units)
  in
  let surfaces = if approved then policy.public_contracts else [] in
  let valid =
    List.filter
      (fun (p : Policy.public_contract) ->
        let unit = resolve_unit p.public_module in
        let owner = Option.bind unit (Hashtbl.find_opt ownerships) in
        let valid =
          List.exists
            (fun (s : Cy.service) -> s.svc_name = p.public_service)
            cy.services
          && ( match owner with
            | Some o -> (
                o.Interpretation.owner_service = p.public_service
                &&
                match o.owner_class with
                | Interpretation.Implementation_of _
                 |Interpretation.Helper_of _ ->
                    true
                | _ -> false )
            | None -> false )
          && List.for_all
               (fun member ->
                 List.mem (p.public_module ^ "." ^ member) obs.defined_values )
               p.public_members
          && List.exists
               (fun (u : Observation.unit_info) ->
                 Some u.canonical = unit && u.fresh )
               obs.units
        in
        if not valid
        then
          gaps :=
            { Observation.gap_code= "GAP-PUBLIC-CONTRACT"
            ; gap_path= p.public_module
            ; gap_detail=
                "owned public surface lacks consistent owner, members or fresh \
                 compiler evidence" }
            :: !gaps ;
        valid )
      surfaces
  in
  let conflicts =
    List.filter
      (fun (p : Policy.public_contract) ->
        List.exists
          (fun (q : Policy.public_contract) ->
            p.public_module = q.public_module && p <> q )
          valid )
      valid
  in
  List.iter
    (fun (p : Policy.public_contract) ->
      gaps :=
        { Observation.gap_code= "GAP-AMBIGUOUS-OWNERSHIP"
        ; gap_path= p.public_module
        ; gap_detail= "conflicting owned public surface declarations" }
        :: !gaps )
    conflicts ;
  ( List.filter (fun p -> not (List.mem p conflicts)) valid
  , List.sort_uniq compare !gaps )

let allowed_surface surfaces ~consumer path =
  List.find_opt
    (fun (p : Policy.public_contract) ->
      List.exists
        (fun member -> path = p.public_module ^ "." ^ member)
        p.public_members
      && (consumer = p.public_service || List.mem consumer p.public_consumers) )
    surfaces
