(* Generated by Well. Do not edit. *)

module Wire = Contract_data_browser.Task_manager

module Request = struct
  type t = Wire.Request.t

  let make value = Wire.Request.make value

  let to_drut value = Wire.Request.to_drut value

  let from_drut text = Wire.Request.from_drut text

  let unknown value = Wire.Request.unknown value

  module Storage = struct
    let to_storage_value value = Wire.Request.Storage.to_storage_value value

    let from_storage_value value = Wire.Request.Storage.from_storage_value value

    let wire_of_storage value = Wire.Request.Storage.wire_of_storage value

    let storage_of_wire text = Wire.Request.Storage.storage_of_wire text
  end
end

module Proxy = struct
  let add ~ctx ~title = Task_manager.add ~ctx ~title
end
