(* Generated by Cyrograf. Do not edit. *)

module Request = struct
  type t = {value: int}

  let make value = {value}

  let to_drut value = string_of_int value.value

  let from_drut text = {value= int_of_string text}

  let unknown value = value

  module Storage = struct
    let to_storage_value value = value.value

    let from_storage_value value = {value}

    let wire_of_storage value = string_of_int value

    let storage_of_wire text = int_of_string text
  end
end
