const root = new URL("../../", import.meta.url).pathname;
const bin = `${root}_build/default/bin/szaniec.exe`;
const decoder = new TextDecoder();
function assert(value: unknown, message: string): asserts value {
  if (!value) throw new Error(message);
}
type Target = { service?: string; method?: string; api?: string };
type Step = {
  kind: string;
  to?: Target;
  reason?: string;
  outcome?: string;
  loopKind?: string;
  site?: { path: string; line: number };
  evidencePath?: string[];
  branches?: { label: string; steps: Step[] }[];
  conditionSteps?: Step[];
  bodySteps?: Step[];
};
type Flow = { status: string; steps: Step[] };
type Method = { name: string; flow: Flow; calls: { to: Target }[] };
type Graph = {
  format: string;
  services: { name: string; methods: Method[] }[];
  entryPoints: { symbol: string; flow: Flow }[];
};
function calls(steps: Step[]): string[] {
  return steps.filter((s) => s.kind === "call" && s.to?.service)
    .map((s) => `${s.to!.service}.${s.to!.method}`);
}
async function run(project: string, ...args: string[]) {
  const result = await new Deno.Command(bin, {
    cwd: project,
    args,
    stdout: "piped",
    stderr: "piped",
  }).output();
  return {
    code: result.code,
    out: decoder.decode(result.stdout),
    err: decoder.decode(result.stderr),
  };
}
Deno.test("ordered source-to-JSON method flows and explicit uncertainty", async () => {
  const project = await Deno.makeTempDir({ prefix: "szaniec-flows-" });
  const write = async (path: string, text: string) => {
    await Deno.mkdir(`${project}/${path.slice(0, path.lastIndexOf("/"))}`, {
      recursive: true,
    });
    await Deno.writeTextFile(`${project}/${path}`, text);
  };
  try {
    const copy = await new Deno.Command("cp", {
      args: ["-R", `${root}test/fixtures/tasks-app/.`, project],
    }).output();
    assert(copy.success, decoder.decode(copy.stderr));
    const contracts: Record<string, string[]> = {
      StoreManager: [
        "place_order",
        "repeated",
        "branching",
        "looping",
        "ambiguous",
        "deferred",
        "throwing",
        "recursive",
        "arguments",
        "callback",
        "periodic",
        "queued",
      ],
      WarehouseAccess: ["validate", "deduce_items"],
      PaymentEngine: ["ensure_paid"],
      PaymentAccess: ["check"],
      CartAccess: ["check"],
      OrdersAccess: ["place_order"],
    };
    for (const [name, methods] of Object.entries(contracts)) {
      await write(
        `lib/contract/${name}.cyrograf`,
        methods.map((m) => `rpc ${m}(Unit) -> Unit`).join("\n") + "\n",
      );
      await write(
        `lib/contract/${name}.ml`,
        "(* Generated by Cyrograf. Do not edit. *)\n" + methods.map((m) =>
          `let ${m} () = ()`
        ).join("\n") + "\n",
      );
    }
    await write(
      "lib/order_app/dune",
      `(include_subdirs unqualified)
(library (name order_app) (wrapped false) (libraries contract well) (flags (:standard -bin-annot)))
`,
    );
    await write(
      "lib/order_app/store_manager/helper.ml",
      `let validate () = WarehouseAccess.validate ()
let rec recursive n = if n > 0 then (validate (); recursive (n - 1))
`,
    );
    await write(
      "lib/order_app/store_manager/store_manager_impl.ml",
      `let place_order () =
  Helper.validate ();
  PaymentEngine.ensure_paid ();
  CartAccess.check ();
  OrdersAccess.place_order ();
  WarehouseAccess.deduce_items ()
let repeated () = Helper.validate (); Helper.validate ()
let branching yes =
  if yes then WarehouseAccess.validate () else CartAccess.check ();
  OrdersAccess.place_order ()
let looping n =
  for _i = 0 to (WarehouseAccess.validate (); n) do Helper.validate () done;
  while (PaymentAccess.check (); false) do CartAccess.check () done;
  OrdersAccess.place_order ()
let ambiguous () =
  WarehouseAccess.validate ();
  (try CartAccess.check () with _ -> PaymentAccess.check ());
  OrdersAccess.place_order ()
let deferred () = let unused () = WarehouseAccess.validate () in ignore unused; OrdersAccess.place_order ()
let throwing () = WarehouseAccess.validate (); raise Exit
let recursive n = Helper.recursive n
let arguments () = ignore (WarehouseAccess.validate (), CartAccess.check ()); OrdersAccess.place_order ()
let callback () = List.iter (fun () -> WarehouseAccess.validate ()) [(); ()]; OrdersAccess.place_order ()
let periodic () = Well.every ~name:"flow" ~sleep:1. (fun () -> WarehouseAccess.validate ()); OrdersAccess.place_order ()
let queued () = ignore (Well.request ~cmd:Task_manager.cmd_topic ~reply:Task_manager.reply_topic ~key:"flow" "value"); OrdersAccess.place_order ()
`,
    );
    await write(
      "lib/order_app/payment_engine/payment_engine_impl.ml",
      "let ensure_paid () = PaymentAccess.check ()\n",
    );
    for (
      const [directory, name, methods] of [
        ["warehouse_access", "WarehouseAccess", contracts.WarehouseAccess],
        ["payment_access", "PaymentAccess", contracts.PaymentAccess],
        ["cart_access", "CartAccess", contracts.CartAccess],
        ["orders_access", "OrdersAccess", contracts.OrdersAccess],
      ] as const
    ) {
      await write(
        `lib/order_app/${directory}/${directory}_impl.ml`,
        methods.map((m) => `let ${m} () = ()`).join("\n") + "\n",
      );
      assert(name.length > 0, "service name");
    }
    await write(
      "lib/order_app/web_client/web_client.ml",
      "let submit () = StoreManager.place_order ()\n",
    );
    const wellPath = `${project}/lib/well_stub/well.ml`;
    await Deno.writeTextFile(
      wellPath,
      await Deno.readTextFile(wellPath) +
        "\nlet every ~name ~sleep callback = ignore (name, sleep, callback)\n",
    );
    let result = await run(project, "approve");
    assert(result.code === 0, result.out + result.err);
    result = await run(project, "check", "--rebuild", "--json");
    const report = JSON.parse(result.out);
    assert(
      !report.findings.some((f: { rule: string }) => f.rule === "GAP-BUILD"),
      result.err + result.out,
    );
    const first = await Deno.readTextFile(`${project}/szaniec.json`);
    const graph: Graph = JSON.parse(first);
    assert(graph.format === "szaniec-callgraph/3", "versioned flow export");
    const method = (service: string, name: string) => {
      const m = graph.services.find((s) => s.name === service)?.methods.find((
        m,
      ) => m.name === name);
      assert(m, `missing ${service}.${name}`);
      return m;
    };
    const manager = (name: string) => method("StoreManager", name);
    const ordered = manager("place_order");
    assert(ordered.flow.status === "complete", JSON.stringify(ordered.flow));
    assert(
      JSON.stringify(calls(ordered.flow.steps)) === JSON.stringify([
        "WarehouseAccess.validate",
        "PaymentEngine.ensure_paid",
        "CartAccess.check",
        "OrdersAccess.place_order",
        "WarehouseAccess.deduce_items",
      ]),
      "source sequence, including continuation after engine",
    );
    assert(
      JSON.stringify(
        calls(method("PaymentEngine", "ensure_paid").flow.steps),
      ) === '["PaymentAccess.check"]',
      "nested engine has a separate flow",
    );
    assert(
      graph.entryPoints.some((e) =>
        e.symbol === "Web_client.submit" &&
        calls(e.flow.steps).includes("StoreManager.place_order")
      ),
      "client entry flow",
    );
    const expanded: string[] = [];
    const expand = (flow: Flow) => {
      for (const step of flow.steps) {
        if (step.kind !== "call" || !step.to?.service) continue;
        expanded.push(`${step.to.service}.${step.to.method}`);
        expand(method(step.to.service, step.to.method!).flow);
      }
    };
    expand(ordered.flow);
    assert(
      expanded.join(",") ===
        "WarehouseAccess.validate,PaymentEngine.ensure_paid,PaymentAccess.check,CartAccess.check,OrdersAccess.place_order,WarehouseAccess.deduce_items",
      "renderer can expand then resume the caller",
    );
    const repeated = manager("repeated");
    assert(
      calls(repeated.flow.steps).length === 2,
      "duplicate helper invocations remain separate",
    );
    assert(
      repeated.calls.filter((c) => c.to.service === "WarehouseAccess")
        .length === 1,
      "dependency edge remains merged",
    );
    const occurrences = repeated.flow.steps.filter((s) =>
      s.to?.service === "WarehouseAccess"
    );
    assert(
      occurrences[0].site?.line === occurrences[1].site?.line,
      "same terminal helper site",
    );
    assert(
      occurrences.every((s) => s.evidencePath?.includes("Helper.validate")),
      "helper provenance",
    );
    const branch = manager("branching").flow;
    assert(
      branch.status === "complete",
      "represented alternatives are complete static evidence",
    );
    const choice = branch.steps.find((s) => s.kind === "choice");
    assert(choice?.branches?.length === 2, "separate conditional arms");
    assert(
      calls(branch.steps).join() === "OrdersAccess.place_order",
      "alternative access calls are not flattened",
    );
    const loop = manager("looping").flow;
    assert(loop.status === "complete", JSON.stringify(loop));
    assert(
      calls(loop.steps).join() ===
        "WarehouseAccess.validate,OrdersAccess.place_order",
      "for bounds outside loop",
    );
    const loops = loop.steps.filter((s) => s.kind === "loop");
    assert(
      loops.length === 2 &&
        calls(loops[0].bodySteps!).join() === "WarehouseAccess.validate",
      "for body",
    );
    assert(
      calls(loops[1].conditionSteps!).join() === "PaymentAccess.check",
      "while condition retained inside loop",
    );
    assert(
      calls(loops[1].bodySteps!).join() === "CartAccess.check",
      "while body",
    );
    assert(
      manager("ambiguous").flow.status === "incomplete",
      "unsupported exceptions remain incomplete",
    );
    assert(
      calls(manager("ambiguous").flow.steps).join() ===
        "WarehouseAccess.validate,OrdersAccess.place_order",
      "known surrounding sequence survives uncertainty",
    );
    assert(
      calls(manager("deferred").flow.steps).join() ===
        "OrdersAccess.place_order",
      "defining a function does not run it",
    );
    assert(
      manager("throwing").flow.steps.some((s) =>
        s.kind === "exit" && s.outcome === "raise"
      ),
      "explicit exceptional exit",
    );
    assert(
      manager("recursive").flow.status === "incomplete",
      "recursive helper expansion terminates visibly",
    );
    const args = manager("arguments").flow;
    assert(
      args.status === "incomplete" &&
        args.steps.some((s) => s.reason?.includes("unspecified")),
      "operand order is not guessed",
    );
    const iterator = manager("callback").flow.steps.find((s) =>
      s.loopKind === "iterator"
    );
    assert(
      iterator &&
        calls(iterator.bodySteps!).join() === "WarehouseAccess.validate",
      "supported eager callback retains repetition",
    );
    assert(
      !calls(manager("periodic").flow.steps).includes(
        "WarehouseAccess.validate",
      ),
      "activation is independent of registration flow",
    );
    assert(
      graph.entryPoints.some((e) =>
        e.symbol.includes("Store_manager_impl.periodic.<callback@") &&
        calls(e.flow.steps).includes("WarehouseAccess.validate")
      ),
      "activation body has a separate entry flow",
    );
    assert(
      manager("queued").flow.steps.some((s) => s.reason),
      "unresolved queued target remains explicit",
    );
    const second = await run(project, "check", "--json");
    assert(
      first === await Deno.readTextFile(`${project}/szaniec.json`),
      "deterministic ordered output",
    );
    assert(
      JSON.stringify(report) === JSON.stringify(JSON.parse(second.out)),
      "new flow evidence does not change report semantics",
    );
    const sourcePath =
      `${project}/lib/order_app/store_manager/store_manager_impl.ml`;
    const future = new Date(Date.now() + 60_000);
    await Deno.utime(sourcePath, future, future);
    const stale = await run(project, "check", "--json");
    assert(stale.code === 2, "stale source remains incomplete analysis");
    const staleGraph: Graph = JSON.parse(
      await Deno.readTextFile(`${project}/szaniec.json`),
    );
    const unavailable = staleGraph.services.find((s) =>
      s.name === "StoreManager"
    )!
      .methods.find((m) => m.name === "place_order")!.flow;
    assert(
      unavailable.status === "incomplete" &&
        unavailable.steps.some((s) => s.kind === "unknown"),
      "unavailable implementation is not an empty complete flow",
    );
  } finally {
    await Deno.remove(project, { recursive: true });
  }
});
