(* Stands in for code generated by `well contract build` from
   contract/AuditClient.toml. *)

module type IMPL = sig
  val record : Well.rpc_ctx -> string -> bool
end

let _service_ref :
    (string -> Well.rpc_ctx -> Yojson.Safe.t -> Yojson.Safe.t) option ref =
  ref None

let make_spec (module I : IMPL) : Well.Service.spec =
  Well.Service.{name= "AuditClient"; handler= ()}

let record ~ctx ~text =
  let req = `String text in
  match !_service_ref with
  | Some f -> (
    match f "record" ctx req with
    | `Bool b -> b
    | _ -> failwith "AuditClient: bad wire" )
  | None -> failwith "AuditClient: service not registered"
