(* Stands in for code generated by `well contract build` from
   contract/FormattingEngine.toml. *)

module type IMPL = sig
  val render : Well.rpc_ctx -> string -> string
end

let _service_ref :
    (string -> Well.rpc_ctx -> Yojson.Safe.t -> Yojson.Safe.t) option ref =
  ref None

let make_spec (module I : IMPL) : Well.Service.spec =
  Well.Service.{name= "FormattingEngine"; handler= ()}

let render ~ctx ~text =
  let req = `String text in
  match !_service_ref with
  | Some f -> (
    match f "render" ctx req with
    | `String s -> s
    | _ -> failwith "FormattingEngine: bad wire" )
  | None -> failwith "FormattingEngine: service not registered"
