(* Stands in for code generated by `well contract build` from
   contract/NotificationManager.toml. *)

module type IMPL = sig
  val publish : Well.rpc_ctx -> string -> bool
end

let _service_ref :
    (string -> Well.rpc_ctx -> Yojson.Safe.t -> Yojson.Safe.t) option ref =
  ref None

let make_spec (module I : IMPL) : Well.Service.spec =
  Well.Service.{name= "NotificationManager"; handler= ()}

let publish ~ctx ~text =
  let req = `String text in
  match !_service_ref with
  | Some f -> (
    match f "publish" ctx req with
    | `Bool b -> b
    | _ -> failwith "NotificationManager: bad wire" )
  | None -> failwith "NotificationManager: service not registered"

let cmd_topic =
  Well.topic "notification.cmd" (fun s -> `String s) (fun _ -> Ok "")

let reply_topic =
  Well.topic "notification.reply" (fun b -> `Bool b) (fun _ -> Ok true)

let event_topic =
  Well.topic "notification.event" (fun s -> `String s) (fun _ -> Ok "")
