(* Stands in for code generated by `well contract build` from
   contract/TaskAccess.toml. Generated-code mechanics live here: message
   types with wire codecs, the IMPL signature, the service ref dispatcher
   and per-method proxy functions. *)

module Task = struct
  type t =
    { id: int
    ; title: string }

  let to_wire (v : t) : Yojson.Safe.t = `List [`Int v.id; `String v.title]

  let of_wire (w : Yojson.Safe.t) : t =
    match w with
    | `List [`Int id; `String title] -> {id; title}
    | _ -> failwith "Task.of_wire"
end

module ListReq = struct
  type t = {limit: int}

  let to_wire (v : t) : Yojson.Safe.t = `List [`Int v.limit]

  let of_wire (w : Yojson.Safe.t) : t =
    match w with
    | `List [`Int limit] -> {limit}
    | _ -> failwith "ListReq.of_wire"
end

module TaskList = struct
  type t = {tasks: Task.t list}

  let of_wire (w : Yojson.Safe.t) : t =
    match w with
    | `List [`List items] -> {tasks= List.map Task.of_wire items}
    | _ -> failwith "TaskList.of_wire"
end

module type IMPL = sig
  val list : Well.rpc_ctx -> ListReq.t -> Task.t list

  val create : Well.rpc_ctx -> string -> Task.t
end

let _service_ref :
    (string -> Well.rpc_ctx -> Yojson.Safe.t -> Yojson.Safe.t) option ref =
  ref None

let make_spec (module I : IMPL) : Well.Service.spec =
  Well.Service.{name= "TaskAccess"; handler= ()}

let list ~ctx ~limit =
  let req = ListReq.to_wire {limit} in
  match !_service_ref with
  | Some f -> TaskList.of_wire (f "list" ctx req)
  | None -> failwith "TaskAccess: service not registered"

let create ~ctx ~title =
  let req = `String title in
  match !_service_ref with
  | Some f -> Task.of_wire (f "create" ctx req)
  | None -> failwith "TaskAccess: service not registered"
