(* Stands in for code generated by `well contract build` from
   contract/TaskManager.toml. *)

module AddReq = struct
  type t = {title: string}

  let to_wire (v : t) : Yojson.Safe.t = `List [`String v.title]
end

module type IMPL = sig
  val list : Well.rpc_ctx -> Task_access.ListReq.t -> Task_access.Task.t list

  val add : Well.rpc_ctx -> AddReq.t -> Task_access.Task.t
end

let _service_ref :
    (string -> Well.rpc_ctx -> Yojson.Safe.t -> Yojson.Safe.t) option ref =
  ref None

let make_spec (module I : IMPL) : Well.Service.spec =
  Well.Service.{name= "TaskManager"; handler= ()}

let list ~ctx ~limit =
  let req = Task_access.ListReq.to_wire {limit} in
  match !_service_ref with
  | Some f -> Task_access.TaskList.of_wire (f "list" ctx req)
  | None -> failwith "TaskManager: service not registered"

let add ~ctx ~title =
  let req = AddReq.to_wire {title} in
  match !_service_ref with
  | Some f -> Task_access.Task.of_wire (f "add" ctx req)
  | None -> failwith "TaskManager: service not registered"

let cmd_topic = Well.topic "task.cmd" (fun s -> `String s) (fun _ -> Ok "")

let reply_topic = Well.topic "task.reply" (fun s -> `String s) (fun _ -> Ok "")
