(* Stands in for code generated by `well contract build` from
   contract/TemplateEngine.toml. *)

module type IMPL = sig
  val expand : Well.rpc_ctx -> string -> string
end

let _service_ref :
    (string -> Well.rpc_ctx -> Yojson.Safe.t -> Yojson.Safe.t) option ref =
  ref None

let make_spec (module I : IMPL) : Well.Service.spec =
  Well.Service.{name= "TemplateEngine"; handler= ()}

let expand ~ctx ~text =
  let req = `String text in
  match !_service_ref with
  | Some f -> (
    match f "expand" ctx req with
    | `String s -> s
    | _ -> failwith "TemplateEngine: bad wire" )
  | None -> failwith "TemplateEngine: service not registered"

let cmd_topic = Well.topic "template.cmd" (fun s -> `String s) (fun _ -> Ok "")

let reply_topic =
  Well.topic "template.reply" (fun s -> `String s) (fun _ -> Ok "")
