(executable
 (name version_gate)
 (modules version_gate)
 (libraries szaniec_program_access szaniec_model szaniec_architecture_access))

(executable
 (name coverage_facts_test)
 (modules coverage_facts_test)
 (libraries szaniec_program_access szaniec_model unix))

(executable
 (name suggestions)
 (modules suggestions)
 (libraries
  szaniec_suggestion_manager
  szaniec_model
  szaniec_architecture_access
  szaniec_model_access))

(rule
 (alias runtest)
 (package szaniec)
 (action
  (run %{exe:version_gate.exe})))

(rule
 (alias runtest)
 (package szaniec)
 (action
  (run %{exe:coverage_facts_test.exe})))

(rule
 (alias runtest)
 (package szaniec)
 (action
  (run %{exe:suggestions.exe})))

(test
 (name config_test)
 (modules config_test)
 (libraries szaniec_config szaniec_model szaniec_architecture_access otoml unix))
