(executable
 (name version_gate)
 (libraries szaniec_program_access szaniec_model szaniec_architecture_access))

(executable
 (name suggestions)
 (libraries
  szaniec_suggestion_manager
  szaniec_model
  szaniec_architecture_access
  szaniec_model_access))

(rule
 (alias runtest)
 (package szaniec)
 (action
  (run %{exe:version_gate.exe})))

(rule
 (alias runtest)
 (package szaniec)
 (action
  (run %{exe:suggestions.exe})))
